# ------------------------------------------------------------------------
# PoET: Pose Estimation Transformer for Single-View, Multi-Object 6D Pose Estimation
# Copyright (c) 2022 Thomas Jantos (thomas.jantos@aau.at), University of Klagenfurt - Control of Networked Systems (CNS). All Rights Reserved.
# Licensed under the BSD-2-Clause-License with no commercial use [see LICENSE for details]
# ------------------------------------------------------------------------
anchor_sizes:
-
  - 32
-
  - 64
-
  - 128
-
  - 256
-
  - 512
backbone_str: resnet50-fpn
input_resize:
- 480
- 640
label_to_category_id:
  background: 0
  obj_000001: 1
  obj_000002: 2
